### ISSUE TITLE
what about some more gui functions?

### ISSUE THREAD

**Issue by 2147483649** [F3XTeam/RBX-Support-Library#3]
Your idea is really great and I have some advice.
I think functions that show gui to client is useful, such as `showAlertDialog(title, message, targetPlayer,button1,button1Action,button2,button2Action){}`, then let the users set the styles by themselves, call a function to show a dialog to a player.
Do you think this is ok?

**Comment by GigsD4X** [comment]
This might be better off as a separate project! 😊 Perhaps this project that Validark is working on may be of use: https://github.com/RoStrap/UI
